name: Build (Forge 1.20.1)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload Artifact (JARs)
        uses: actions/upload-artifact@v4
        with:
          name: spiritcaller-player-wings
          path: build/libs/*.jar
          if-no-files-found: error
